"""Add column image to Cupon model

Revision ID: 08223acb71fb
Revises: 841ea446d156
Create Date: 2023-12-28 02:31:47.653820

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '08223acb71fb'
down_revision = '841ea446d156'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('coupon', sa.Column('image', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('coupon', 'image')
    # ### end Alembic commands ###
