"""add tables for reality project

Revision ID: 09d446f53008
Revises: 49c8838aea28
Create Date: 2022-06-22 18:49:17.686256

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '09d446f53008'
down_revision = '49c8838aea28'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
