"""add notifications json

Revision ID: 0b0bfe250805
Revises: 3ea7a49601d6
Create Date: 2022-06-30 17:31:29.505528

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '0b0bfe250805'
down_revision = '3ea7a49601d6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('notification', 'type',
               existing_type=sa.INTEGER(),
               type_=sa.String(),
               nullable=False)
    op.alter_column('notification', 'data',
               existing_type=sa.INTEGER(),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('notification', 'data',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.alter_column('notification', 'type',
               existing_type=sa.String(),
               type_=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
