"""is invited

Revision ID: 1dca26744f0e
Revises: b1ee00f4ddbc
Create Date: 2022-09-28 04:10:56.390492

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1dca26744f0e'
down_revision = 'b1ee00f4ddbc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('is_invited', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'is_invited')
    # ### end Alembic commands ###
