"""add json

Revision ID: 2bb7c4895cda
Revises: deac03654d57
Create Date: 2022-07-17 19:21:14.060046

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2bb7c4895cda'
down_revision = 'deac03654d57'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
