"""Add places table and relations

Revision ID: 5391fc0f156f
Revises: 3fca13b47572
Create Date: 2024-01-03 17:42:47.870320

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5391fc0f156f'
down_revision = '3fca13b47572'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('places',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('lat', sa.String(), nullable=True),
    sa.Column('lng', sa.String(), nullable=True),
    sa.Column('radius', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id', 'owner_id')
    )
    op.create_index(op.f('ix_places_id'), 'places', ['id'], unique=False)
    op.add_column('couponassigned', sa.Column('id', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_couponassigned_id'), 'couponassigned', ['id'], unique=False)
    op.drop_column('couponassigned', 'redeemed')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('couponassigned', sa.Column('redeemed', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_couponassigned_id'), table_name='couponassigned')
    op.drop_column('couponassigned', 'id')
    op.drop_index(op.f('ix_places_id'), table_name='places')
    op.drop_table('places')
    # ### end Alembic commands ###
