"""unique contacts

Revision ID: 6a90f2eb497c
Revises: f21c77d32e3e
Create Date: 2022-06-29 13:48:26.882513

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6a90f2eb497c'
down_revision = 'f21c77d32e3e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('_owner_contact_uc', 'contact', ['owner_id', 'contact_id'])
    op.drop_constraint('contact_contact_id_fkey', 'contact', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('contact_contact_id_fkey', 'contact', 'user', ['contact_id'], ['id'])
    op.drop_constraint('_owner_contact_uc', 'contact', type_='unique')
    # ### end Alembic commands ###
