"""remove users

Revision ID: 841ea446d156
Revises: 975414514de1
Create Date: 2023-05-16 13:48:46.239546

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '841ea446d156'
down_revision = '975414514de1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
