"""Add column id autogen to Cuponapp model

Revision ID: 8d984d20e2ad
Revises: b22aa66f0ae7
Create Date: 2024-01-02 18:19:30.457598

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8d984d20e2ad'
down_revision = 'b22aa66f0ae7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
