"""update reports 

Revision ID: 9122dd8de0e4
Revises: c86db4b2454d
Create Date: 2022-06-29 11:56:44.941723

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9122dd8de0e4'
down_revision = 'c86db4b2454d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('report', sa.Column('category', sa.String(), nullable=True))
    op.add_column('report', sa.Column('title', sa.String(), nullable=True))
    op.alter_column('report', 'description',
               existing_type=sa.INTEGER(),
               type_=sa.String(),
               existing_nullable=True)
    op.create_index(op.f('ix_report_category'), 'report', ['category'], unique=False)
    op.drop_column('report', 'problem')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('report', sa.Column('problem', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_report_category'), table_name='report')
    op.alter_column('report', 'description',
               existing_type=sa.String(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.drop_column('report', 'title')
    op.drop_column('report', 'category')
    # ### end Alembic commands ###
