"""fix path_1 to path

Revision ID: 975414514de1
Revises: 44c809dd0193
Create Date: 2023-01-14 19:35:31.741253

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '975414514de1'
down_revision = '44c809dd0193'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('asset', 'path_1', nullable=True, new_column_name='path')


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('asset', 'path', nullable=True, new_column_name='path_1')
    # ### end Alembic commands ###
