"""add locked to contacts

Revision ID: 9e53abe29814
Revises: 2bb7c4895cda
Create Date: 2022-07-21 00:38:21.273212

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9e53abe29814'
down_revision = '3e12be642267'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contact', sa.Column('locked', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('contact', 'locked')
    # ### end Alembic commands ###
