"""Change cupon model and relations

Revision ID: a47b3cee41af
Revises: 8d984d20e2ad
Create Date: 2024-01-03 14:56:27.158979

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'a47b3cee41af'
down_revision = '8d984d20e2ad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_couponapp_id', table_name='couponapp')
    op.drop_table('couponapp')
    op.add_column('asset', sa.Column('coupon_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'asset', 'coupon', ['coupon_id'], ['id'])
    op.add_column('coupon', sa.Column('owner_id', sa.Integer(), nullable=False))
    op.add_column('coupon', sa.Column('img', sa.String(), nullable=True))
    op.add_column('coupon', sa.Column('expiration_date', sa.DateTime(), nullable=False))
    op.add_column('coupon', sa.Column('start_date', sa.DateTime(), nullable=True))
    op.add_column('coupon', sa.Column('active', sa.Boolean(), nullable=True))
    op.drop_constraint('coupon_asset_id_fkey', 'coupon', type_='foreignkey')
    op.create_foreign_key(None, 'coupon', 'user', ['owner_id'], ['id'])
    op.drop_column('coupon', 'asset_id')
    op.drop_column('coupon', 'start')
    op.drop_column('coupon', 'expiration')
    op.drop_column('coupon', 'time')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('coupon', sa.Column('time', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('coupon', sa.Column('expiration', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.add_column('coupon', sa.Column('start', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('coupon', sa.Column('asset_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'coupon', type_='foreignkey')
    op.create_foreign_key('coupon_asset_id_fkey', 'coupon', 'asset', ['asset_id'], ['id'])
    op.drop_column('coupon', 'active')
    op.drop_column('coupon', 'start_date')
    op.drop_column('coupon', 'expiration_date')
    op.drop_column('coupon', 'img')
    op.drop_column('coupon', 'owner_id')
    op.drop_constraint(None, 'asset', type_='foreignkey')
    op.drop_column('asset', 'coupon_id')
    op.create_table('couponapp',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('owner_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('img', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('terms', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('quantity', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('expiration_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('start_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], name='couponapp_owner_id_fkey'),
    sa.PrimaryKeyConstraint('id', 'owner_id', name='couponapp_pkey')
    )
    op.create_index('ix_couponapp_id', 'couponapp', ['id'], unique=False)
    # ### end Alembic commands ###
