"""Add cuponredeem table and relations

Revision ID: a8d6c34cc1ce
Revises: 5391fc0f156f
Create Date: 2024-01-03 18:01:35.304872

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a8d6c34cc1ce'
down_revision = '5391fc0f156f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('couponreedeemed',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('coupon_id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['coupon_id'], ['coupon.id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id', 'coupon_id', 'owner_id')
    )
    op.create_index(op.f('ix_couponreedeemed_id'), 'couponreedeemed', ['id'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_couponreedeemed_id'), table_name='couponreedeemed')
    op.drop_table('couponreedeemed')
    # ### end Alembic commands ###
