"""add json

Revision ID: b1819fb0ab7a
Revises: df50f34ff1c8
Create Date: 2022-07-17 19:20:24.406687

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b1819fb0ab7a'
down_revision = 'df50f34ff1c8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
