"""add start to coupon

Revision ID: b1ee00f4ddbc
Revises: da3563f33dc2
Create Date: 2022-09-27 02:40:58.503345

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b1ee00f4ddbc'
down_revision = 'da3563f33dc2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('coupon', sa.Column('start', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('coupon', 'start')
    # ### end Alembic commands ###
