"""Add column id autogen to Cuponapp model

Revision ID: b22aa66f0ae7
Revises: e1c4349a98b7
Create Date: 2024-01-02 17:20:13.780133

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b22aa66f0ae7'
down_revision = 'e1c4349a98b7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
