"""add asset location

Revision ID: b33e28feb375
Revises: 1dca26744f0e
Create Date: 2022-09-28 05:27:21.528603

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b33e28feb375'
down_revision = '1dca26744f0e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assetlocation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lat', sa.String(length=128), nullable=True),
    sa.Column('lng', sa.String(length=128), nullable=True),
    sa.Column('rule', sa.String(length=128), nullable=True),
    sa.Column('asset_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['asset_id'], ['asset.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_assetlocation_id'), 'assetlocation', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_assetlocation_id'), table_name='assetlocation')
    op.drop_table('assetlocation')
    # ### end Alembic commands ###
