"""add status to reports

Revision ID: bd4beb97d52b
Revises: 702469d97724
Create Date: 2022-06-29 12:52:30.561367

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bd4beb97d52b'
down_revision = '702469d97724'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('report', sa.Column('status', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('report', 'status')
    # ### end Alembic commands ###
