"""delete places and add redeemed cupons with new realations

Revision ID: c540b00390a8
Revises: 54043ac81b2d
Create Date: 2024-01-04 14:13:19.367363

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'c540b00390a8'
down_revision = '54043ac81b2d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_places_id', table_name='places')
    op.drop_table('places')
    op.add_column('couponreedeemed', sa.Column('admin_id', sa.Integer(), nullable=False))
    op.drop_column('couponreedeemed', 'place_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('couponreedeemed', sa.Column('place_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('couponreedeemed', 'admin_id')
    op.create_table('places',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('owner_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('lat', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('lng', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('radius', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], name='places_owner_id_fkey'),
    sa.PrimaryKeyConstraint('id', 'owner_id', name='places_pkey')
    )
    op.create_index('ix_places_id', 'places', ['id'], unique=True)
    # ### end Alembic commands ###
