"""add tables for reality project

Revision ID: c86db4b2454d
Revises: ecec92b4fb72
Create Date: 2022-06-22 19:11:09.781118

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c86db4b2454d'
down_revision = 'ecec92b4fb72'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
