"""time coupon

Revision ID: da3563f33dc2
Revises: 9fcc4deb452e
Create Date: 2022-08-28 02:02:39.577585

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'da3563f33dc2'
down_revision = '9fcc4deb452e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('asset', 'path',
               existing_type=sa.VARCHAR(length=128),
               nullable=True)
    op.add_column('coupon', sa.Column('time', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('coupon', 'time')
    op.alter_column('asset', 'path',
               existing_type=sa.VARCHAR(length=128),
               nullable=False)
    # ### end Alembic commands ###
