"""add json

Revision ID: deac03654d57
Revises: b1819fb0ab7a
Create Date: 2022-07-17 19:20:59.278937

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'deac03654d57'
down_revision = 'b1819fb0ab7a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
