"""add voucher table

Revision ID: dee762b76d8e
Revises: 91480bfc092c
Create Date: 2022-08-08 21:12:34.161815

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dee762b76d8e'
down_revision = '91480bfc092c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('asset',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('path', sa.String(length=128), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_asset_id'), 'asset', ['id'], unique=False)
    op.create_table('coupon',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('terms', sa.String(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('expiration', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['asset.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_coupon_id'), 'coupon', ['id'], unique=False)
    op.create_table('couponassigned',
    sa.Column('coupon_id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('redeemed', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['coupon_id'], ['coupon.id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('coupon_id', 'owner_id')
    )
    op.add_column('contact', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('contact', sa.Column('updated_at', sa.DateTime(), nullable=False))
    op.add_column('location', sa.Column('updated_at', sa.DateTime(), nullable=False))
    op.add_column('notification', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('notification', sa.Column('updated_at', sa.DateTime(), nullable=False))
    op.add_column('report', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('report', sa.Column('updated_at', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('report', 'updated_at')
    op.drop_column('report', 'created_at')
    op.drop_column('notification', 'updated_at')
    op.drop_column('notification', 'created_at')
    op.drop_column('location', 'updated_at')
    op.drop_column('contact', 'updated_at')
    op.drop_column('contact', 'created_at')
    op.drop_table('couponassigned')
    op.drop_index(op.f('ix_coupon_id'), table_name='coupon')
    op.drop_table('coupon')
    op.drop_index(op.f('ix_asset_id'), table_name='asset')
    op.drop_table('asset')
    # ### end Alembic commands ###
