"""Add cuponapp tabl

Revision ID: e1c4349a98b7
Revises: 08223acb71fb
Create Date: 2024-01-02 16:35:24.626625

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e1c4349a98b7'
down_revision = '08223acb71fb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('couponapp',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('img', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('terms', sa.String(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('expiration_date', sa.DateTime(), nullable=False),
    sa.Column('start_date', sa.DateTime(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id', 'owner_id')
    )
    op.create_index(op.f('ix_couponapp_id'), 'couponapp', ['id'], unique=False)
    op.drop_column('coupon', 'image')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('coupon', sa.Column('image', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_couponapp_id'), table_name='couponapp')
    op.drop_table('couponapp')
    # ### end Alembic commands ###
