"""add contact id

Revision ID: f21c77d32e3e
Revises: bd4beb97d52b
Create Date: 2022-06-29 13:11:00.161417

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f21c77d32e3e'
down_revision = 'bd4beb97d52b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contact', sa.Column('contact_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'contact', 'user', ['contact_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'contact', type_='foreignkey')
    op.drop_column('contact', 'contact_id')
    # ### end Alembic commands ###
